<?php
/**
 * Book or Rent
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    BookorRent
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class CategoryData {

	public $table = 'categories';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2013-10-29 06:33:35',
			'modified' => '2013-12-12 07:27:10',
			'parent_id' => '0',
			'name' => 'Sports',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '2',
			'created' => '2013-10-29 06:33:49',
			'modified' => '2013-11-22 14:32:15',
			'parent_id' => '1',
			'name' => 'Training',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'training',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '3',
			'created' => '2013-10-29 06:33:59',
			'modified' => '2013-11-22 11:12:22',
			'parent_id' => '1',
			'name' => 'Ball Sports',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'ball-sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '4',
			'created' => '2013-10-29 06:34:11',
			'modified' => '2013-11-22 11:12:36',
			'parent_id' => '1',
			'name' => 'Outdoor Sports',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'outdoor-sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '5',
			'created' => '2013-10-29 06:34:21',
			'modified' => '2013-11-22 11:13:05',
			'parent_id' => '1',
			'name' => 'Water Sports',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'water-sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '6',
			'created' => '2013-10-29 06:34:38',
			'modified' => '2013-11-22 11:13:12',
			'parent_id' => '1',
			'name' => 'Winter Sports',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'winter-sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '7',
			'created' => '2013-10-29 06:35:01',
			'modified' => '2013-11-22 11:13:20',
			'parent_id' => '1',
			'name' => 'Combat Sports',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'combat-sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '8',
			'created' => '2013-10-29 06:35:14',
			'modified' => '2013-11-22 11:13:29',
			'parent_id' => '1',
			'name' => 'Cliff & Air Sports',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'cliff-air-sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '9',
			'created' => '2013-10-29 06:35:25',
			'modified' => '2013-11-22 11:13:40',
			'parent_id' => '1',
			'name' => 'Other Sports',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-sports',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '10',
			'created' => '2013-10-29 06:35:43',
			'modified' => '2013-12-12 07:31:53',
			'parent_id' => '0',
			'name' => 'Food & Drink',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'food-drink',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '11',
			'created' => '2013-10-29 06:36:07',
			'modified' => '2013-11-22 11:14:38',
			'parent_id' => '10',
			'name' => 'Cooking & Mixology',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'cooking-mixology',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '12',
			'created' => '2013-10-29 06:36:21',
			'modified' => '2013-11-22 11:14:48',
			'parent_id' => '10',
			'name' => 'Dinners & Brunches',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'dinners-brunches',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '13',
			'created' => '2013-10-29 06:36:42',
			'modified' => '2013-11-22 11:14:58',
			'parent_id' => '10',
			'name' => 'BBQs & Picnics',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'bbqs-picnics',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '14',
			'created' => '2013-10-29 06:36:55',
			'modified' => '2013-11-22 11:15:26',
			'parent_id' => '10',
			'name' => 'Potlucks',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'potlucks',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '15',
			'created' => '2013-10-29 06:37:51',
			'modified' => '2013-11-22 11:15:35',
			'parent_id' => '10',
			'name' => 'Food & Drinks Experiences',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'food-drinks-experiences',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '16',
			'created' => '2013-10-29 06:38:09',
			'modified' => '2013-11-22 11:15:47',
			'parent_id' => '10',
			'name' => 'Let\'s Try A Restaurant',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'let-s-try-a-restaurant',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '17',
			'created' => '2013-10-29 06:38:21',
			'modified' => '2013-11-22 11:15:57',
			'parent_id' => '10',
			'name' => 'Let\'s Go For Drinks',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'let-s-go-for-drinks',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '18',
			'created' => '2013-10-29 06:38:36',
			'modified' => '2013-11-22 11:16:04',
			'parent_id' => '10',
			'name' => 'Other Food & Drink',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-food-drink',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '19',
			'created' => '2013-10-29 06:39:06',
			'modified' => '2013-12-12 07:33:07',
			'parent_id' => '0',
			'name' => 'Learning & Culture',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'learning-culture',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '20',
			'created' => '2013-10-29 06:39:15',
			'modified' => '2013-11-22 11:16:56',
			'parent_id' => '19',
			'name' => 'Art & Crafts',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'art-crafts',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '21',
			'created' => '2013-10-29 06:39:33',
			'modified' => '2013-11-22 11:16:50',
			'parent_id' => '19',
			'name' => 'Photo & Video',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'photo-video',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '22',
			'created' => '2013-10-29 06:39:41',
			'modified' => '2013-11-22 11:17:23',
			'parent_id' => '19',
			'name' => 'Languages',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'languages',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '23',
			'created' => '2013-10-29 06:39:52',
			'modified' => '2013-11-22 11:17:38',
			'parent_id' => '19',
			'name' => 'Music, Dance & Acting',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'music-dance-acting',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '24',
			'created' => '2013-10-29 06:40:03',
			'modified' => '2013-11-22 11:17:45',
			'parent_id' => '19',
			'name' => 'Galleries & Museums',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'galleries-museums',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '25',
			'created' => '2013-10-29 06:40:12',
			'modified' => '2013-11-22 11:17:58',
			'parent_id' => '19',
			'name' => 'Lifestyle & Wellness',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'lifestyle-wellness',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '26',
			'created' => '2013-10-29 06:40:44',
			'modified' => '2013-11-22 11:18:38',
			'parent_id' => '19',
			'name' => 'Management & Technology',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'management-technology',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '27',
			'created' => '2013-10-29 06:40:54',
			'modified' => '2013-11-22 11:18:58',
			'parent_id' => '19',
			'name' => 'Other Learning & Culture',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-learning-culture',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '28',
			'created' => '2013-10-29 06:41:07',
			'modified' => '2013-12-12 07:34:26',
			'parent_id' => '0',
			'name' => 'Social',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'social',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '29',
			'created' => '2013-10-29 06:41:24',
			'modified' => '2013-11-22 11:19:41',
			'parent_id' => '28',
			'name' => 'Parties',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'parties',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '30',
			'created' => '2013-10-29 06:41:34',
			'modified' => '2013-11-22 11:19:47',
			'parent_id' => '28',
			'name' => 'Day Trips & Adventures',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'day-trips-adventures',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '31',
			'created' => '2013-10-29 06:41:43',
			'modified' => '2013-11-22 11:19:53',
			'parent_id' => '28',
			'name' => 'Performances',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'performances',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '32',
			'created' => '2013-10-29 06:41:56',
			'modified' => '2013-11-22 11:20:05',
			'parent_id' => '28',
			'name' => 'Lets Play A Game',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'lets-play-a-game',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '33',
			'created' => '2013-10-29 06:42:12',
			'modified' => '2013-11-22 11:20:14',
			'parent_id' => '28',
			'name' => 'Movies & Shows',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'movies-shows',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '34',
			'created' => '2013-10-29 06:42:26',
			'modified' => '2013-11-22 11:20:20',
			'parent_id' => '28',
			'name' => 'Meet-ups',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'meet-ups',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '35',
			'created' => '2013-10-29 06:42:49',
			'modified' => '2013-11-22 11:20:30',
			'parent_id' => '28',
			'name' => 'Community Craziness',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'community-craziness',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '36',
			'created' => '2013-10-29 06:43:00',
			'modified' => '2013-11-22 11:20:38',
			'parent_id' => '28',
			'name' => 'Other Social',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-social',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '37',
			'created' => '2013-10-29 06:43:28',
			'modified' => '2013-12-12 07:35:51',
			'parent_id' => '0',
			'name' => 'Skills',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'skills',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '38',
			'created' => '2013-10-29 06:43:48',
			'modified' => '2013-12-04 09:08:22',
			'parent_id' => '37',
			'name' => 'HandyWork',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'handywork',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '39',
			'created' => '2013-10-29 06:45:40',
			'modified' => '2013-12-04 09:08:32',
			'parent_id' => '37',
			'name' => 'Childcare',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'childcare',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '40',
			'created' => '2013-10-29 06:45:48',
			'modified' => '2013-12-04 09:08:41',
			'parent_id' => '37',
			'name' => 'Tutoring',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'tutoring',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '41',
			'created' => '2013-10-29 06:45:57',
			'modified' => '2013-12-04 09:08:50',
			'parent_id' => '37',
			'name' => 'Pet Care',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'pet-care',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '42',
			'created' => '2013-10-29 06:46:07',
			'modified' => '2013-12-04 09:09:00',
			'parent_id' => '37',
			'name' => 'Event Help',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'event-help',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '43',
			'created' => '2013-10-29 06:46:21',
			'modified' => '2013-12-04 09:09:07',
			'parent_id' => '37',
			'name' => 'Creative Skills',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'creative-skills',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '44',
			'created' => '2013-10-29 06:46:34',
			'modified' => '2013-12-04 09:08:14',
			'parent_id' => '37',
			'name' => 'Health & Wellness',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'health-wellness',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '45',
			'created' => '2013-10-29 06:46:44',
			'modified' => '2013-12-04 09:09:45',
			'parent_id' => '37',
			'name' => 'Other Skills',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-skills',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '46',
			'created' => '2013-10-29 06:47:46',
			'modified' => '2013-12-12 07:37:10',
			'parent_id' => '0',
			'name' => 'Space Sharing',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'space-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '47',
			'created' => '2013-10-29 06:47:56',
			'modified' => '2013-12-04 09:16:33',
			'parent_id' => '46',
			'name' => 'House Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'house-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '48',
			'created' => '2013-10-29 06:48:05',
			'modified' => '2013-12-04 09:16:45',
			'parent_id' => '46',
			'name' => 'Couch Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'couch-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '49',
			'created' => '2013-10-29 06:48:15',
			'modified' => '2013-12-04 09:16:52',
			'parent_id' => '46',
			'name' => 'Sports Venue',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'sports-venue',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '50',
			'created' => '2013-10-29 06:48:31',
			'modified' => '2013-12-04 09:16:59',
			'parent_id' => '46',
			'name' => 'Garden Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'garden-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '51',
			'created' => '2013-10-29 06:48:41',
			'modified' => '2013-12-04 09:17:06',
			'parent_id' => '46',
			'name' => 'Event Space',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'event-space',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '52',
			'created' => '2013-10-29 06:49:17',
			'modified' => '2013-12-04 09:17:12',
			'parent_id' => '46',
			'name' => 'Workspace Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'workspace-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '53',
			'created' => '2013-10-29 06:49:31',
			'modified' => '2013-12-04 09:17:44',
			'parent_id' => '46',
			'name' => 'Parking Spots',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'parking-spots',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '54',
			'created' => '2013-10-29 06:50:41',
			'modified' => '2013-12-04 09:17:50',
			'parent_id' => '46',
			'name' => 'Other Space Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-space-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '55',
			'created' => '2013-10-29 06:50:53',
			'modified' => '2013-12-12 07:38:48',
			'parent_id' => '0',
			'name' => 'Item Sharing',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'item-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '56',
			'created' => '2013-10-29 06:51:05',
			'modified' => '2013-12-04 09:18:44',
			'parent_id' => '55',
			'name' => 'Tool Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'tool-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '57',
			'created' => '2013-10-29 06:51:15',
			'modified' => '2013-12-04 09:18:50',
			'parent_id' => '55',
			'name' => 'Sports Equipment Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'sports-equipment-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '58',
			'created' => '2013-10-29 06:51:24',
			'modified' => '2013-12-04 09:19:00',
			'parent_id' => '55',
			'name' => 'Gadgets & Game Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'gadgets-game-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '59',
			'created' => '2013-10-29 06:51:35',
			'modified' => '2013-12-04 09:19:07',
			'parent_id' => '55',
			'name' => 'Music Equipment Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'music-equipment-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '60',
			'created' => '2013-10-29 06:51:45',
			'modified' => '2013-12-04 09:19:13',
			'parent_id' => '55',
			'name' => 'Event Supplies Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'event-supplies-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '61',
			'created' => '2013-10-29 06:52:11',
			'modified' => '2013-12-04 09:19:20',
			'parent_id' => '55',
			'name' => 'Bike Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'bike-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '62',
			'created' => '2013-10-29 06:52:20',
			'modified' => '2013-12-04 09:19:26',
			'parent_id' => '55',
			'name' => 'Boat Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'boat-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '63',
			'created' => '2013-10-29 06:52:28',
			'modified' => '2013-12-04 09:19:34',
			'parent_id' => '55',
			'name' => 'Other Item Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-item-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '64',
			'created' => '2013-10-29 06:52:48',
			'modified' => '2013-12-12 07:39:37',
			'parent_id' => '0',
			'name' => 'Smarter Living',
			'description' => 'Fusce et erat vitae augue ultricies interdum. In vehicula rutrum magna pulvinar tempus.',
			'slug' => 'smarter-living',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '65',
			'created' => '2013-10-29 06:54:15',
			'modified' => '2013-12-04 09:20:54',
			'parent_id' => '64',
			'name' => 'Ride Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'ride-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '66',
			'created' => '2013-10-29 06:54:29',
			'modified' => '2013-12-04 09:21:01',
			'parent_id' => '64',
			'name' => 'Errand & Delivery',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'errand-delivery',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '67',
			'created' => '2013-10-29 06:54:45',
			'modified' => '2013-12-04 09:21:08',
			'parent_id' => '64',
			'name' => 'Moving Help',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'moving-help',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '68',
			'created' => '2013-10-29 06:54:56',
			'modified' => '2013-12-04 09:21:20',
			'parent_id' => '64',
			'name' => 'Brunch & Meal Service',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'brunch-meal-service',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '69',
			'created' => '2013-10-29 06:55:07',
			'modified' => '2013-12-04 09:21:28',
			'parent_id' => '64',
			'name' => 'Lunch Sharing',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'lunch-sharing',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '70',
			'created' => '2013-10-29 06:55:17',
			'modified' => '2013-12-04 09:21:37',
			'parent_id' => '64',
			'name' => 'Volunteer Opportunities',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'volunteer-opportunities',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '71',
			'created' => '2013-10-29 06:55:53',
			'modified' => '2013-12-04 09:21:46',
			'parent_id' => '64',
			'name' => 'Random Acts Of Kindness',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'random-acts-of-kindness',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
		array(
			'id' => '72',
			'created' => '2013-10-29 06:56:09',
			'modified' => '2013-12-04 09:21:55',
			'parent_id' => '64',
			'name' => 'Other Smarter Living',
			'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temporris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
			'slug' => 'other-smarter-living',
			'item_count' => '0',
			'request_count' => '0',
			'category_type_count' => '0',
			'is_active' => '1'
		),
	);

}
