<?php
/**
 * Book or Rent
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    BookorRent
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class FormFieldStepData {

	public $table = 'form_field_steps';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2013-10-29 07:01:00',
			'modified' => '2013-10-29 07:01:24',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '2',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '2',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '3',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '3',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '4',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '4',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '5',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '5',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '6',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '6',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '7',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '7',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '8',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '8',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '9',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '9',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '11',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '10',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '12',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '11',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '13',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '12',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '14',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '13',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '15',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '14',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '16',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '15',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '17',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '16',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '18',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '17',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '20',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '18',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '21',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '19',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '22',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '20',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '23',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '21',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '24',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '22',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '25',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '23',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '26',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '24',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '27',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '25',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '29',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '26',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '30',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '27',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '31',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '28',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '32',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '29',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '33',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '30',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '34',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '31',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '35',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '32',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '36',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '33',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '38',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '34',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '39',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '35',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '40',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '36',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '41',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '37',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '42',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '38',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '43',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '39',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '44',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '40',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '45',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '41',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '47',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '42',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '48',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '43',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '49',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '44',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '50',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '45',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '51',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '46',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '52',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '47',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '53',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '48',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '54',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '49',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '56',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '50',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '57',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '51',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '58',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '52',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '59',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '53',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '60',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '54',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '61',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '55',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '62',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '56',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '63',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '57',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '65',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '58',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '66',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '59',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '67',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '60',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '68',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '61',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '69',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '62',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '70',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '63',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '71',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '64',
			'created' => '2016-02-04 19:12:46',
			'modified' => '2016-02-04 19:12:46',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '72',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
		array(
			'id' => '65',
			'created' => '2013-10-29 07:01:00',
			'modified' => '2013-10-29 07:01:24',
			'name' => 'Basic Info',
			'slug' => '',
			'category_id' => '',
			'info' => 'Basic Info',
			'order' => '1',
			'is_deletable' => '',
			'is_splash' => '',
			'additional_info' => '',
			'is_payment_step' => '',
			'is_editable' => '1',
			'is_payout_step' => '',
			'is_show_in_request_form' => '1'
		),
	);

}
