<?php
/**
 * Book or Rent
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    BookorRent
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class UserData {

	public $table = 'users';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2009-04-28 10:09:35',
			'modified' => '2014-07-04 08:37:55',
			'role_id' => '1',
			'attachment_id' => '229',
			'username' => 'admin',
			'email' => 'productdemo.admin@gmail.com',
			'password' => '$1$Iz]ZII12$tTb.EuP3eScxM50yqQ52S.',
			'available_wallet_amount' => '0.00',
			'blocked_amount' => '0.00',
			'cleared_amount' => '0.00',
			'total_amount_withdrawn' => '0.00',
			'total_withdraw_request_count' => '0',
			'total_amount_deposited' => '0.00',
			'item_feedback_count' => '0',
			'host_expired_count' => '0',
			'host_canceled_count' => '0',
			'host_rejected_count' => '0',
			'host_completed_count' => '0',
			'host_review_count' => '0',
			'host_confirmed_count' => '0',
			'host_waiting_for_acceptance_count' => '0',
			'host_booking_request_count' => '0',
			'host_payment_cleared_count' => '0',
			'host_total_booked_count' => '0',
			'host_total_lost_booked_count' => '0',
			'host_total_earned_amount' => '0.00',
			'host_total_lost_amount' => '0.00',
			'host_total_pipeline_amount' => '0.00',
			'host_total_site_revenue' => '0.00',
			'booking_expired_count' => '0',
			'booking_rejected_count' => '0',
			'booking_canceled_count' => '0',
			'booking_review_count' => '0',
			'booking_completed_count' => '0',
			'booking_confirmed_count' => '0',
			'booking_payment_pending_count' => '0',
			'booking_waiting_for_acceptance_count' => '0',
			'booker_booking_request_count' => '0',
			'booking_payment_cleared_count' => '0',
			'booker_positive_feedback_count' => '0',
			'booker_item_user_count' => '0',
			'booking_total_booked_count' => '0',
			'booking_total_booked_amount' => '0.00',
			'booking_total_lost_booked_count' => '0',
			'booking_total_site_revenue' => '0.00',
			'positive_feedback_count' => '0',
			'item_favorite_count' => '6',
			'item_user_count' => '0',
			'request_count' => '0',
			'item_count' => '0',
			'item_pending_approval_count' => '0',
			'item_inactive_count' => '0',
			'referred_by_user_id' => '0',
			'referred_by_user_count' => '0',
			'referred_booking_count' => '0',
			'affiliate_refer_booking_count' => '0',
			'user_referred_count' => '0',
			'total_commission_pending_amount' => '0.00',
			'total_commission_canceled_amount' => '0.00',
			'total_commission_completed_amount' => '0.00',
			'commission_line_amount' => '0.00',
			'commission_withdraw_request_amount' => '0.00',
			'commission_paid_amount' => '0.00',
			'user_login_count' => '1',
			'user_view_count' => '1',
			'user_friend_count' => '0',
			'user_comment_count' => '0',
			'cookie_hash' => '0682b4ee5683deadfc5c3d56d73e947f',
			'cookie_time_modified' => '2012-07-09 11:43:47',
			'is_agree_terms_conditions' => '1',
			'is_active' => '1',
			'is_email_confirmed' => '1',
			'is_affiliate_user' => '',
			'ip_id' => '0',
			'last_login_ip_id' => '1',
			'last_logged_in_time' => '2014-07-04 08:37:55',
			'user_facebook_friend_count' => '418',
			'is_show_facebook_friends' => '1',
			'is_facebook_friends_fetched' => '1',
			'network_fb_user_id' => '1653423181',
			'last_facebook_friend_fetched_date' => '2011-11-15',
			'is_paid' => '1',
			'security_question_id' => '0',
			'security_answer' => '',
			'is_facebook_register' => '',
			'is_twitter_register' => '',
			'is_google_register' => '',
			'is_googleplus_register' => '',
			'is_yahoo_register' => '',
			'is_linkedin_register' => '',
			'is_openid_register' => '',
			'facebook_user_id' => '',
			'facebook_access_token' => '',
			'twitter_user_id' => '',
			'twitter_access_token' => '',
			'twitter_access_key' => '',
			'google_user_id' => '',
			'google_access_token' => '',
			'googleplus_user_id' => '',
			'yahoo_user_id' => '',
			'yahoo_access_token' => '',
			'linkedin_user_id' => '',
			'linkedin_access_token' => '',
			'openid_user_id' => '',
			'twitter_avatar_url' => '',
			'google_avatar_url' => '',
			'googleplus_avatar_url' => '',
			'linkedin_avatar_url' => '',
			'facebook_friends_count' => '0',
			'twitter_followers_count' => '0',
			'google_contacts_count' => '0',
			'googleplus_contacts_count' => '0',
			'yahoo_contacts_count' => '0',
			'linkedin_contacts_count' => '0',
			'user_openid_count' => '0',
			'is_skipped_fb' => '1',
			'is_skipped_twitter' => '1',
			'is_skipped_google' => '1',
			'is_skipped_yahoo' => '1',
			'is_skipped_linkedin' => '',
			'is_facebook_connected' => '',
			'is_twitter_connected' => '',
			'is_google_connected' => '',
			'is_googleplus_connected' => '',
			'is_yahoo_connected' => '',
			'is_linkedin_connected' => '',
			'site_state_id' => '0',
			'user_avatar_source_id' => '1',
			'mobile_app_hash' => '',
			'mobile_app_time_modified' => '0000-00-00 00:00:00',
			'is_idle' => '1',
			'is_item_posted' => '',
			'is_requested' => '',
			'is_item_booked' => '',
			'invite_count' => '0',
			'activity_message_id' => '0',
			'payment_gateway_id' => '0',
			'sudopay_pay_key' => '',
			'sudopay_gateway_id' => '0',
			'sudopay_payment_id' => '0',
			'sudopay_revised_amount' => '0.00',
			'sudopay_token' => '',
			'pwd_reset_token' => '',
			'pwd_reset_requested_date' => '0000-00-00 00:00:00',
			'sudopay_receiver_account_id' => '0'
		),
	);

}
